### ISSUE TITLE
I watched the Demo seriously, but I have a few questions I want to consult

### ISSUE THREAD

**Issue by enjoy-wind** [cassidoo/accordion#18]
1. Naming problem: What does "CC" in AccordionCC mean?
2. Code issue:What is the Accordion function in App.final.js?
3. Design question: Why does the App function content not use data to render the view principle in App.final.js.?

**Comment by cassidoo** [comment]
Hey! When you say you saw the demo, which one did you see? Some of that should answer your questions depending on what you saw.

1. CC stands for Compound Component! It's just a way of differentiating between the two styles of writing.
2. The Accordion in App.final.js is the same thing as the original version, except it shows the tab content as well. In the talks I gave using this code, I extend the original one first with that.
3. I think I understand your question. The purpose of this demo and the talks was to show that you don't need a single source of truth and point of entry in a compound component. The users of your components and arrange and rearrange data with the components, and play and experiment with them, without conforming to the structure of a JSON object that expects the exact same input each time. You can still pass in JSON, and then use these components with it! It's all about flexibility.

**Comment by enjoy-wind** [comment]
Thank you, you are a warm-hearted fairy with a sweet smile.
